background = "#eff1f5"
border = "#bcc0cc"
terminal_border = "#04a5e5"
selection = "#dce0e8"
session_selection = "#ccd0da"
title = "#1e66f5"
text = "#4c4f69"
dimmed = "#acb0be"
hint = "#209fb5"
running = "#40a02b"
waiting = "#df8e1d"
idle = "#9ca0b0"
error = "#d20f39"
terminal_active = "#1e66f5"
group = "#179299"
search = "#7287fd"
accent = "#fe640b"
